# Adapted from: https://github.com/leouieda/cv/blob/master/Makefile
# Licensed under BDS 3: https://github.com/leouieda/cv/blob/master/LICENSE.txt


# The name of the main .tex file to build.
# Other files can be included into this one.
DOCUMENT = cv
PDF = $(DOCUMENT).pdf

LATEX_FLAGS = -halt-on-error
LATEX = xelatex
PDFVIEWER = skim

# Folder where the figure files are (will assume they are EPSs or PNGs)
FIGS = figures

# File Types (for dependencies)
TEX = $(wildcard *.tex)
BIB = $(wildcard *.bib)
STY = $(wildcard *.sty)
CLS = $(wildcard *.cls)
BST = $(wildcard *.bst)


# ================================================================ #
#                             Builds                               #
# ================================================================ #

all: $(PDF)

bib: bibtex $(DOCUMENT)

%.pdf: %.tex $(STY) $(CLS) $(BIB) $(BST) $(EPS) $(PNG)
	$(LATEX) $(LATEX_FLAGS) $<
	$(LATEX) $(LATEX_FLAGS) $< 1>/dev/null

show: all
	@ # Redirect stdout and stderr to /dev/null for silent execution
	@ (${PDFVIEWER} $(PDF) > /dev/null 2>&1 & )

### Clean
# This target cleans the temporary files generated by the tex programs
clean:
	rm -rf *.aux *.log *.bbl *.blg *.out *.toc
	rm -rf $(PDF)
	rm -rf $(FIGS)/*-eps-converted-to.pdf
